### ISSUE TITLE
Pokemons of gym are printed multiple times sometimes

### ISSUE THREAD

**Issue by matejos** [mseleng/Kodemon#205] opened 2016-12-15 20:32 UTC
Log in as Psyxox, fight some gyms, look into Saffron city gym (Psyxox's gym), see this:
![image](https://cloud.githubusercontent.com/assets/10269067/21240969/ef8e7bd4-c30d-11e6-8eae-2139b022c5dc.png)

**Comment by mseleng** [comment] 2016-12-15 20:40
Well, this is weird, isn't it? Gym leaders has no way of getting new Pokémon. Do you have any further details to reproduce this? Eg. does this happen even when you first time select that gym? Or after some fights?

**Comment by matejos** [comment] 2016-12-15 20:48
If you look closer, it's just those same 5 pokemons again and again. Seems like after every successful fight it prints another copy, or so.

**Comment by mseleng** [comment] 2016-12-15 20:59
That is weird, because a Pokemon that loses doesn't change at all (level, etc). I would expect behavior like this when for example pokemon levels up, which may create a new one (instead of updating) but the pokemon listed has the same levels (Pokemon that are listed ultiple times) so I think that it may be a bug on ui. I'll check it out

**Comment by mseleng** [comment] 2016-12-16 00:07
This is probably somehow connected to hibernate, because I am not able to reproduce this problem when  running in debug mode, and going slowly through the code. Also, interesting thing is that calling gymFacade.findById() returns "wrong" instance, eg. one with trainer with 20 pokemons, but when I call gymFacade.findAll() and click to the saffron gym, I see correct data

**Comment by mseleng** [comment] 2016-12-16 09:30
Resolved in #214 . needs further research

**Closed by mseleng** 2016-12-16 09:30 UTC
Labels: bug, optional-high priority
